language: node_js
node_js:
  - 12.16.2
cache:
  directories:
    - ~/.npm
before_script:
  - npm install -g npm@latest
  - npm install
  - npm install jest-expo
  - npm install -g expo-cli
script:
  - npm ci
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - prettier --check .
        - npm test
        - npm ci
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive
